### ISSUE TITLE
Results are Differential to OpenSSL

### ISSUE THREAD

**Issue by DaniWi** [kokke/tiny-ECDH-c#11]
I tried to compare the public keys which are created from your algorithm with the result from OpenSSL but the created keys are different. I used the the sect163r2 curve.

Do you have tested your version against OpenSSL or LibreSSL?

**Comment by kokke** [comment]
Hi @DaniWi - thanks for your interest :)

This library is still is development and is probably not compatible with any other libraries than itself.
There are still bugs in the code and open issues, so please don't attempt to use this in production at least :)

I hope this answers your questions, so I am closing the issue.
Feel free to keep commenting though, if you have suggestions or further questions :)
