### ISSUE TITLE
NIST_K571   NIST_K409

### ISSUE THREAD

**Issue by Andyvff** [kokke/tiny-ECDH-c#20]
NIST_K571  
const gf2elem_t coeff_b    = { 0x00000001,

NIST_K409  
const gf2elem_t coeff_b    = { 0x00000001,

**Comment by kokke** [comment]
Hi @Andyvff - can you please elaborate the question a bit? I'm not sure what you are hinting at :)

**Comment by Andyvff** [comment]
You need to fix these bits. And then 409 and 571 work. ;)





пн, 6 апр. 2020 г. в 21:37, kokke <notifications@github.com>:

**Comment by kokke** [comment]
:D!

Thanks a lot. If you want to be in the contributors list, make a PR and I will accept it :)

**Comment by Andyvff** [comment]
Add ECDSA. code in fork. need test
https://www.youtube.com/playlist?list=PLHwjNvYEPHoRHkaBJk7y8r4FG_fxD3QY3     ;)

**Comment by kokke** [comment]
Hi @Andyvff - that is awesome :)

I will see if I can get some testing done on your fork tonight.

**Comment by kokke** [comment]
@Andyvff what is the XPSR assembly stuff doing?

I don't have access to any ARM hardware I ran run it on, and I'm having trouble compiling the example. 

What are you using as the hash in the verification-step ?

**Comment by Andyvff** [comment]
automatic translation from Russian.

I am not a mathematician. therefore there may be errors in the program. I wrote the program under stm32. I checked on it. The place where this is important is long plus and long minus, there is an analysis of overflow, which is taken from the processor register.{XPSR()}  The private key, K and Hash are all generated in a random sequence.  I checked the logic code in C #, Biginteger.

added by ecdh_example.c

u32 iran;
u32 Random(void){
iran=(iran*(u32)4096+(u32)150889)%(u32)714025;
return iran;
};

**Comment by kokke** [comment]
Hi @Andyvff - can you upload the STM32 code you've been testing with?

I can't find the Random function in your github repository, so maybe it is not the same as the code from the youtube-videos?

I would very much like to get ECDSA working, and if your changes work on the STM32, I think it should be possible to port the changes and merge them into the project :)

**Comment by Andyvff** [comment]
replaced by prng_next ;)

вт, 12 мая 2020 г. в 14:20, kokke <notifications@github.com>:
