### ISSUE TITLE
ECDH and ECDSA

### ISSUE THREAD

**Issue by as135-can** [kokke/tiny-ECDH-c#21]
Hii,

In this code both ECDH and ECDSA working ?

**Comment by kokke** [comment]
Hi @as135-can and thanks for your interest 👍 

Currently, only ECDH is officially supported, but [@Andyfvv](https://github.com/Andyvff) has a fork going with ECDSA I believe - see https://github.com/kokke/tiny-ECDH-c/issues/20

Andy's fork is available from https://github.com/Andyvff/tiny-ECDH-c/
