### ISSUE TITLE
Representation of generated Public Key

### ISSUE THREAD

**Issue by sergio-domingues** [kokke/tiny-ECDH-c#8]
Hello, I'm using sect163k1 elliptic curve and in order to generate the public key I'm executing the following code:

```C
int ecdh_generate_keys(uint8_t* public, uint8_t* private);
```

Is the result following a standard specification (compressed / uncompressed / hybrid) format defined in [SEC1v2](http://www.secg.org/sec1-v2.pdf)? 

Thanks in advance!

**Comment by kokke** [comment]
Hi @sergio-domingues and thanks for your interest :)

I am not sure I understand your question. 
The keys are generated in a standard fashion.

From the comments in the top of [ecdh_example.c](https://github.com/kokke/tiny-ECDH-c/blob/master/ecdh_example.c).

>   1. Alice picks a (secret) random natural number 'a', calculates P = a * G and sends P to Bob.
>      'a' is Alice's private key. 
>      'P' is Alice's public key.

The coordinates are represented as uncompressed raw points, which to my knowledge is a standard representation.

Does that answer your question?

**Comment by sergio-domingues** [comment]
According to the standards defined in that NIST specification, shouldn't the uncompressed format begin with 0x04? I know If it's better for my needs I can just add that initial byte, I just wanted to clarify what standard is being used. Thanks again :)

**Comment by kokke** [comment]
I think it mostly means something if you exchange curve parameters using a standard format like X.509 or something similar (ASN.1?).

I will close this issue, but feel free to continue the discussion if you have further questions or comments :)

**Comment by sergio-domingues** [comment]
Hi again @kokke, I also noticed that a 3 byte (0x00) is being added after X and Y, is it supposed to work like a separator?

**Comment by kokke** [comment]
Hi @sergio-domingues - I'm not sure what you are referring to, can you give me a link to some code or copy/paste the parts you are referring to ? :)

**Comment by sergio-domingues** [comment]
Testing for a K=1 with curves sec163k1, sect233k1 adds bytes between coordinates (3 bytes and 2 bytes respectively). For example for the k233:
![image](https://user-images.githubusercontent.com/9081358/41407490-7da9bcaa-6fc7-11e8-86fc-7a47b3889a30.png)

**Comment by kokke** [comment]
That is just a coincidence. An artifact of how the numbers are placed in memory.

For the case sect163k1, think of the key as two 163 bits numbers put next to each other (the x and y coordinate).

We allocate in 8 bit chunks (8 bit pr byte), so that leaves at least 5 unused bits after the first coordinate.
Unless the y coordinate uses the MSB, every bit unused, will leave an extra 0-bit between the numbers.

It is not unthinkable that there could be 20-25 clear bits between the numbers.

**Comment by sergio-domingues** [comment]
Yeah I understand that the public key is represented by the concatenation of x and y. But following that logic on your reply the unused bytes will be in the 0-30 byte range (233 bits), but every time a public key  is generated for that curve a 2 byte (0x00) is added between x and y: [x-coord][0x0][0x0][y-coord] and the y-coord is missing the 2 bytes because of that spacing.
